### PR TITLE
Small updates

### PR DESCRIPTION
**Pull request by CreeperMario**
Hi.

This PR includes a few small changes to make some things clearer - the tutorial was mostly really well written and informative.

I do have a few remaining questions, throughout the day I'll perform some tests to get those answered. Those include:
* You mentioned that your example code does not return to the foreground correctly - I'll see if I can fix that
* You also mentioned that the TV screen frame buffer size changes depending on what resolution the console is set to output - from my experience the OSScreen buffer has always been 1280x720 regardless of resolution or aspect ratio, though I may be wrong, its been a while since I've fiddled with OSScreen. I'll test this.

### CODE REVIEW

**Comment by ashquarky** [comment]
I'm not sure there's much that can be done about the foreground stuff - I guess you could register for ProcUI callbacks but that adds a big layer of complexity... Given it's the first code most people will see, I'm not sure it's worth it. It's not like it matters for HBL anyway - something is very wrong with HBL, and going in and out of the background when running through it pretty efficiently breaks it; as I'm sure you'd know.
Re: OSScreen, I've definitely seen a few apps misbehave when running at 480i/480p/576i (common when using analog video) so I assume the framebuffer size is different. Can't hurt to make people be cautious, y'know?

**Comment by CreeperMario** [comment]
> I guess you could register for ProcUI callbacks but that adds a big layer of complexity

I was under the impression that I would not need to do this, as your frame buffers are stored in the default heap rather than in MEM1 where they would need to be removed during process transition. After further testing, I found that the OSScreen functions fiddle around with the GPU registers (stored in `0xFC000000` and onwards [[1]](https://wiiubrew.org/wiki/Cafe_OS#Virtual_Memory_Map)[[2]](https://wiiubrew.org/wiki/Hardware/Espresso_Registers#GX2_Registers)) which, thinking about it now, actually makes a lot of sense. It also makes sense that the background process would not be allowed to access them. The solution, of course, does involve using `ProcUIRegisterCallback` to shut down OSScreen while the program is still in the foreground, which as you said is out of the scope of this tutorial.

> I've definitely seen a few apps misbehave when running at 480i/480p/576i (common when using analog video) so I assume the framebuffer size is different.

I just finished testing this, and I can confirm that, regardless of the cable type, screen resolution or aspect ratio (I tested all combinations), the OSScreen TV frame buffer is always exactly 1280x720 in size, and is scaled/stretched to fit the target screen resolution/aspect ratio. The allocated block of memory for the TV frame buffer is also always `0x708000` bytes in size. I tested this by adding the following code to your example app that draws a green border along the top/left edges of the buffer (leaving a 100 pixel gap at the end)

```c
for(int i = 0; i < 1180; i++) {
   OSScreenPutPixelEx(SCREEN_TV, i, 0, 0x00FF00FF);
   OSScreenPutPixelEx(SCREEN_TV, i, 1, 0x00FF00FF);
   OSScreenPutPixelEx(SCREEN_TV, i, 2, 0x00FF00FF);
   OSScreenPutPixelEx(SCREEN_TV, i, 3, 0x00FF00FF);
   OSScreenPutPixelEx(SCREEN_TV, i, 4, 0x00FF00FF);
}

for(int i = 0; i < 620; i++) {
   OSScreenPutPixelEx(SCREEN_TV, 0, i, 0x00FF00FF);
   OSScreenPutPixelEx(SCREEN_TV, 1, i, 0x00FF00FF);
   OSScreenPutPixelEx(SCREEN_TV, 2, i, 0x00FF00FF);
   OSScreenPutPixelEx(SCREEN_TV, 3, i, 0x00FF00FF);
   OSScreenPutPixelEx(SCREEN_TV, 4, i, 0x00FF00FF);
}
```

I'm curious as to which programs don't display correctly in the 480/576i modes - are they official Nintendo licensed programs that use GX2 (because I know that GX2 has settings to change the frame buffer size based on the screen resolution) or other homebrew programs using OSScreen?

**Comment by ashquarky** [comment]
The misbehaviour was some very old OSScreen applications (C@VE and the like). That said, I've also looked at this and you're right, it doesn't seem to have any effect. Maybe it was something to do with the AVM workarounds people were using?
In any case, it does look like OSScreen isn't affected by the TV connection, at least on PAL consoles. I guess I'll take that bit out of the tutorial.

**Comment by CreeperMario** [comment]
> Maybe it was something to do with the AVM workarounds people were using?

Yeah, that would have been my fault. 😅

**Pull request merged**
